import React, { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useLanguage } from '../../context/LanguageContext';
import { useRouter } from '../../core/router/Router';
import { ROUTES } from '../../theme/routes';
import { UserPlus, Mail, Lock, User, ArrowRight, CheckCircle2, Code2 } from 'lucide-react';

export const RegisterPage: React.FC = () => {
  const { register } = useAuth();
  const { t } = useLanguage();
  const { navigate } = useRouter();

  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [termsAccepted, setTermsAccepted] = useState(true);
  const [loading, setLoading] = useState(false);
  const [responseToken, setResponseToken] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!termsAccepted) return;
    setLoading(true);

    const res = await register(firstName, lastName, email, password);
    setLoading(false);

    if (res.success && res.token) {
      setResponseToken(res.token);
    }
  };

  return (
    <div className="max-w-lg mx-auto py-12">
      <div className="bg-[var(--bg-surface)] p-8 rounded-3xl border border-[var(--border-default)] shadow-xl space-y-6">
        
        {/* Header */}
        <div className="text-center space-y-2">
          <div className="w-12 h-12 rounded-2xl bg-indigo-600 text-white mx-auto flex items-center justify-center shadow-lg shadow-indigo-600/30">
            <UserPlus className="w-6 h-6" />
          </div>
          <h1 className="text-2xl font-extrabold text-[var(--text-primary)] tracking-tight">
            {t('auth.register.title')}
          </h1>
          <p className="text-xs text-[var(--text-secondary)]">
            {t('auth.register.subtitle')}
          </p>
        </div>

        {/* If Registration Response Received */}
        {responseToken ? (
          <div className="p-6 bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-200 dark:border-emerald-800 rounded-2xl space-y-4">
            <div className="flex items-center gap-3 text-emerald-700 dark:text-emerald-300">
              <CheckCircle2 className="w-6 h-6 text-emerald-500 flex-shrink-0" />
              <div>
                <h3 className="text-sm font-bold">Registration Successful</h3>
                <p className="text-xs text-emerald-600 dark:text-emerald-400">
                  Verification token generated by Spring Boot AuthService.
                </p>
              </div>
            </div>

            <div className="p-3 bg-white dark:bg-black/40 rounded-xl border border-emerald-200 dark:border-emerald-800/60 space-y-1 font-mono text-xs">
              <span className="text-[10px] text-emerald-600 font-bold uppercase tracking-wider block">
                SPRING BOOT API RESPONSE
              </span>
              <p className="text-emerald-800 dark:text-emerald-200 break-all">
                verificationToken: "{responseToken}"
              </p>
            </div>

            <div className="flex gap-3 pt-2">
              <button
                onClick={() => navigate(`${ROUTES.VERIFY_EMAIL}?token=${responseToken}`)}
                className="flex-1 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs rounded-xl shadow-md transition-all flex items-center justify-center gap-2 cursor-pointer"
              >
                <span>Verify Email Now</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-4">
            
            <div className="grid grid-cols-2 gap-4">
              {/* First Name */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-[var(--text-primary)] uppercase tracking-wider">
                  {t('auth.register.firstName')}
                </label>
                <div className="relative">
                  <User className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--text-secondary)]" />
                  <input
                    type="text"
                    required
                    value={firstName}
                    onChange={(e) => setFirstName(e.target.value)}
                    placeholder="Sandeep"
                    className="w-full pl-10 pr-4 py-2.5 text-xs rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-raised)] text-[var(--text-primary)] focus:outline-none focus:ring-2 focus:ring-[var(--brand-primary)]"
                  />
                </div>
              </div>

              {/* Last Name */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-[var(--text-primary)] uppercase tracking-wider">
                  {t('auth.register.lastName')}
                </label>
                <input
                  type="text"
                  required
                  value={lastName}
                  onChange={(e) => setLastName(e.target.value)}
                  placeholder="Prasad"
                  className="w-full px-4 py-2.5 text-xs rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-raised)] text-[var(--text-primary)] focus:outline-none focus:ring-2 focus:ring-[var(--brand-primary)]"
                />
              </div>
            </div>

            {/* Email Field */}
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-[var(--text-primary)] uppercase tracking-wider">
                {t('auth.register.email')}
              </label>
              <div className="relative">
                <Mail className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--text-secondary)]" />
                <input
                  type="email"
                  required
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="sandeep.prasad@example.com"
                  className="w-full pl-10 pr-4 py-2.5 text-xs rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-raised)] text-[var(--text-primary)] focus:outline-none focus:ring-2 focus:ring-[var(--brand-primary)]"
                />
              </div>
            </div>

            {/* Password Field */}
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-[var(--text-primary)] uppercase tracking-wider">
                {t('auth.register.password')}
              </label>
              <div className="relative">
                <Lock className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--text-secondary)]" />
                <input
                  type="password"
                  required
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Password123!"
                  className="w-full pl-10 pr-4 py-2.5 text-xs rounded-xl border border-[var(--border-default)] bg-[var(--bg-surface-raised)] text-[var(--text-primary)] focus:outline-none focus:ring-2 focus:ring-[var(--brand-primary)]"
                />
              </div>
            </div>

            {/* Terms Checkbox */}
            <label className="flex items-center gap-2.5 cursor-pointer pt-1">
              <input
                type="checkbox"
                checked={termsAccepted}
                onChange={(e) => setTermsAccepted(e.target.checked)}
                className="w-4 h-4 rounded text-[var(--brand-primary)] border-[var(--border-default)] focus:ring-[var(--brand-primary)]"
              />
              <span className="text-xs text-[var(--text-secondary)]">
                {t('auth.register.terms')}
              </span>
            </label>

            {/* Submit */}
            <button
              type="submit"
              disabled={loading || !termsAccepted}
              className="w-full py-3 bg-[var(--brand-primary)] text-white hover:bg-[var(--brand-hover)] rounded-xl font-bold text-xs shadow-md transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
            >
              <span>{loading ? t('status.loading') : t('auth.register.submitBtn')}</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </form>
        )}

        {/* Navigation to Sign In */}
        <div className="text-center pt-2 border-t border-[var(--border-default)]">
          <p className="text-xs text-[var(--text-secondary)]">
            {t('auth.register.alreadyAccount')}{' '}
            <button
              onClick={() => navigate(ROUTES.LOGIN)}
              className="font-bold text-[var(--brand-primary)] hover:underline cursor-pointer ml-1"
            >
              {t('auth.register.signInLink')}
            </button>
          </p>
        </div>

      </div>
    </div>
  );
};
