export const PERMISSIONS = {
  // Product Scope
  PRODUCT: {
    VIEW: 'PRODUCT_VIEW',
    CREATE: 'PRODUCT_CREATE',
    UPDATE: 'PRODUCT_UPDATE',
    DELETE: 'PRODUCT_DELETE',
    APPROVE: 'PRODUCT_APPROVE',
  },
  // Category Scope
  CATEGORY: {
    VIEW: 'CATEGORY_VIEW',
    MANAGE: 'CATEGORY_MANAGE',
  },
  // Inventory Scope
  INVENTORY: {
    VIEW: 'INVENTORY_VIEW',
    UPDATE: 'INVENTORY_UPDATE',
  },
  // Order Scope
  ORDER: {
    VIEW: 'ORDER_VIEW',
    CREATE: 'ORDER_CREATE',
    UPDATE: 'ORDER_UPDATE',
    CANCEL: 'ORDER_CANCEL',
    RETURN: 'ORDER_RETURN',
  },
  // Cart & Wishlist
  SHOPPING: {
    CART_MANAGE: 'CART_MANAGE',
    WISHLIST_MANAGE: 'WISHLIST_MANAGE',
  },
  // Reviews
  REVIEW: {
    CREATE: 'REVIEW_CREATE',
    EDIT: 'REVIEW_EDIT',
    DELETE: 'REVIEW_DELETE',
    RESPOND: 'REVIEW_RESPOND',
  },
  // Coupons & Discounts
  COUPON: {
    VIEW: 'COUPON_VIEW',
    CREATE: 'COUPON_CREATE',
    MANAGE: 'COUPON_MANAGE',
  },
  // Payment & Refund
  PAYMENT: {
    VIEW: 'PAYMENT_VIEW',
    MANAGE: 'PAYMENT_MANAGE',
    REFUND_ISSUE: 'REFUND_ISSUE',
  },
  // Shipping
  SHIPPING: {
    MANAGE: 'SHIPPING_MANAGE',
  },
  // User Management
  USER: {
    VIEW: 'USER_VIEW',
    CREATE: 'USER_CREATE',
    UPDATE: 'USER_UPDATE',
    DELETE: 'USER_DELETE',
    MANAGE: 'USER_MANAGE',
    PROFILE_MANAGE: 'PROFILE_MANAGE',
  },
  // Seller Scope
  SELLER: {
    APPROVE: 'SELLER_APPROVE',
    ANALYTICS_VIEW: 'SELLER_ANALYTICS_VIEW',
  },
  // Support & Content
  SUPPORT: {
    TICKET_CREATE: 'SUPPORT_TICKET_CREATE',
    TICKET_MANAGE: 'SUPPORT_TICKET_MANAGE',
    CMS_MANAGE: 'CMS_MANAGE',
  },
  // Analytics & Reports
  ANALYTICS: {
    REPORT_VIEW: 'REPORT_VIEW',
    REPORT_EXPORT: 'REPORT_EXPORT',
    VIEW: 'ANALYTICS_VIEW',
  },
  // System & Super Admin Scope
  SYSTEM: {
    ROLE_MANAGE: 'ROLE_MANAGE',
    PERMISSION_MANAGE: 'PERMISSION_MANAGE',
    ADMIN_MANAGE: 'ADMIN_MANAGE',
    SETTINGS: 'SYSTEM_SETTINGS',
    PLATFORM_CONFIG: 'PLATFORM_CONFIG',
    DATABASE_BACKUP: 'DATABASE_BACKUP',
    DATABASE_RESTORE: 'DATABASE_RESTORE',
    FEATURE_FLAG_MANAGE: 'FEATURE_FLAG_MANAGE',
    API_KEY_MANAGE: 'API_KEY_MANAGE',
    AUDIT_VIEW: 'AUDIT_VIEW',
    IMPERSONATE_USER: 'IMPERSONATE_USER',
    GLOBAL_NOTIFICATION_SEND: 'GLOBAL_NOTIFICATION_SEND',
  },
} as const;

export type PermissionCode =
  | typeof PERMISSIONS.PRODUCT[keyof typeof PERMISSIONS.PRODUCT]
  | typeof PERMISSIONS.CATEGORY[keyof typeof PERMISSIONS.CATEGORY]
  | typeof PERMISSIONS.INVENTORY[keyof typeof PERMISSIONS.INVENTORY]
  | typeof PERMISSIONS.ORDER[keyof typeof PERMISSIONS.ORDER]
  | typeof PERMISSIONS.SHOPPING[keyof typeof PERMISSIONS.SHOPPING]
  | typeof PERMISSIONS.REVIEW[keyof typeof PERMISSIONS.REVIEW]
  | typeof PERMISSIONS.COUPON[keyof typeof PERMISSIONS.COUPON]
  | typeof PERMISSIONS.PAYMENT[keyof typeof PERMISSIONS.PAYMENT]
  | typeof PERMISSIONS.SHIPPING[keyof typeof PERMISSIONS.SHIPPING]
  | typeof PERMISSIONS.USER[keyof typeof PERMISSIONS.USER]
  | typeof PERMISSIONS.SELLER[keyof typeof PERMISSIONS.SELLER]
  | typeof PERMISSIONS.SUPPORT[keyof typeof PERMISSIONS.SUPPORT]
  | typeof PERMISSIONS.ANALYTICS[keyof typeof PERMISSIONS.ANALYTICS]
  | typeof PERMISSIONS.SYSTEM[keyof typeof PERMISSIONS.SYSTEM];
