export const PERMISSIONS = {
  // Product Permissions
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_EDIT: 'PRODUCT_EDIT',
  PRODUCT_DELETE: 'PRODUCT_DELETE',
  PRODUCT_APPROVE: 'PRODUCT_APPROVE',

  // Order Permissions
  ORDER_VIEW: 'ORDER_VIEW',
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_UPDATE: 'ORDER_UPDATE',
  ORDER_CANCEL: 'ORDER_CANCEL',
  ORDER_SHIP: 'ORDER_SHIP',

  // User Permissions
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_MANAGE: 'USER_MANAGE',
  USER_BLOCK: 'USER_BLOCK',

  // Seller Permissions
  SELLER_VIEW: 'SELLER_VIEW',
  SELLER_APPROVE: 'SELLER_APPROVE',
  SELLER_REJECT: 'SELLER_REJECT',
  SELLER_SUSPEND: 'SELLER_SUSPEND',

  // Payment Permissions
  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_MANAGE: 'PAYMENT_MANAGE',
  PAYMENT_REFUND: 'PAYMENT_REFUND',

  // Shipping & Inventory
  SHIPPING_VIEW: 'SHIPPING_VIEW',
  SHIPPING_UPDATE: 'SHIPPING_UPDATE',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_MANAGE: 'INVENTORY_MANAGE',

  // Reviews, Wishlist, Cart
  REVIEW_VIEW: 'REVIEW_VIEW',
  REVIEW_CREATE: 'REVIEW_CREATE',
  REVIEW_MODERATE: 'REVIEW_MODERATE',
  REVIEW_DELETE: 'REVIEW_DELETE',
  REVIEW_REPLY: 'REVIEW_REPLY',
  WISHLIST_MANAGE: 'WISHLIST_MANAGE',
  CART_MANAGE: 'CART_MANAGE',

  // Governance & Admin
  MEDIA_UPLOAD: 'MEDIA_UPLOAD',
  MEDIA_DELETE: 'MEDIA_DELETE',
  COUPON_MANAGE: 'COUPON_MANAGE',
  ANALYTICS_VIEW: 'ANALYTICS_VIEW',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',
  ROLE_MANAGE: 'ROLE_MANAGE',
  PERMISSION_MANAGE: 'PERMISSION_MANAGE',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  SETTINGS_UPDATE: 'SETTINGS_UPDATE',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
