export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/api/auth/register',
    LOGIN: '/api/auth/login',
    LOGOUT: '/api/auth/logout',
    CHANGE_PASSWORD: '/api/auth/change-password',
    FORGOT_PASSWORD: '/api/auth/forgot-password',
    RESET_PASSWORD: '/api/auth/reset-password',
    RESEND_VERIFICATION: '/api/auth/resend-verification',
    VERIFY_EMAIL: '/api/auth/verify-email',
    REFRESH_TOKEN: '/api/auth/refresh-token',
  },
  USERS: {
    PROFILE: '/api/users/profile',
  },
  PRODUCTS: {
    BASE: '/api/products',
    BY_ID: (id: string) => `/api/products/${id}`,
    IMAGE: (productId: string) => `/api/products/${productId}/image`,
    BULK: '/api/products/bulk',
    SEARCH: '/api/products/search',
    FILTER_PRICE: '/api/products/filter/price',
    FILTER_OUT_OF_STOCK: '/api/products/filter/out-of-stock',
    FILTER_IN_STOCK: '/api/products/filter/in-stock',
    FILTER_CATEGORY: (categoryId: string) => `/api/products/filter/category/${categoryId}`,
  },
  CATEGORIES: {
    BASE: '/api/categories',
    BY_ID: (id: string) => `/api/categories/${id}`,
  },
  CART: {
    BASE: '/api/cart',
    ADD: (productId: string) => `/api/cart/${productId}`,
    ITEM: (cartItemId: string) => `/api/cart/items/${cartItemId}`,
  },
  ORDERS: {
    BASE: '/api/orders',
    BY_ID: (id: string) => `/api/orders/${id}`,
    MY_ORDERS: '/api/orders/my-orders',
    CANCEL: (id: string) => `/api/orders/${id}/cancel`,
  },
  PAYMENTS: {
    BASE: '/api/payments',
    BY_ID: (paymentId: string) => `/api/payments/${paymentId}`,
    BY_ORDER: (orderId: string) => `/api/payments/order/${orderId}`,
    BY_STATUS: (status: string) => `/api/payments/status/${status}`,
    BY_TRANSACTION: (transactionId: string) => `/api/payments/transaction/${transactionId}`,
    SUCCESS: (paymentId: string) => `/api/payments/${paymentId}/success`,
    FAILED: (paymentId: string) => `/api/payments/${paymentId}/failed`,
    CANCEL: (paymentId: string) => `/api/payments/${paymentId}/cancel`,
    REFUND: (paymentId: string) => `/api/payments/${paymentId}/refund`,
    RETRY: (paymentId: string) => `/api/payments/${paymentId}/retry`,
  },
  ADDRESSES: {
    BASE: '/api/addresses',
    BY_ID: (addressId: string) => `/api/addresses/${addressId}`,
    DEFAULT: '/api/addresses/default',
    SET_DEFAULT: (addressId: string) => `/api/addresses/${addressId}/default`,
  },
  WISHLIST: {
    BASE: '/api/wishlist',
    ITEM: (productId: string) => `/api/wishlist/${productId}`,
  },
  INVENTORY: {
    BY_PRODUCT: (productId: string) => `/api/inventory/${productId}`,
  },
  MEDIA: {
    BASE: '/api/media',
    UPLOAD: '/api/media/upload',
    BY_ID: (id: string) => `/api/media/${id}`,
    BY_USER: (userId: string) => `/api/media/user/${userId}`,
  },
  LANGUAGES: {
    BASE: '/api/languages',
    BY_ID: (id: string) => `/api/languages/${id}`,
    ENABLED: '/api/languages/enabled',
    BY_CODE: (code: string) => `/api/languages/code/${code}`,
    ENABLE: (id: string) => `/api/languages/${id}/enable`,
    DISABLE: (id: string) => `/api/languages/${id}/disable`,
    DEFAULT: (id: string) => `/api/languages/${id}/default`,
  },
  TRANSLATIONS: {
    KEYS: '/api/translations/keys',
    KEY_BY_ID: (id: string) => `/api/translations/keys/${id}`,
    VALUES: '/api/translations/values',
    VALUE_BY_ID: (id: string) => `/api/translations/values/${id}`,
    MAP: (languageCode: string) => `/api/translations/map/${languageCode}`,
    BY_LANGUAGE: (languageCode: string) => `/api/translations/language/${languageCode}`,
  },
  ROLES: {
    BASE: '/api/roles',
    ASSIGN: '/api/roles/assign',
    REMOVE: '/api/roles/remove',
  },
};
