export interface ApiEndpointSpec {
  id: string;
  category: 'Auth' | 'User' | 'Product' | 'Role' | 'Test';
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  path: string;
  summary: string;
  access: 'Public' | 'Authenticated' | 'ROLE_ADMIN' | 'ROLE_USER';
  requestBody?: string;
  responseBody?: string;
  curlExample: string;
}

export const API_ENDPOINTS: ApiEndpointSpec[] = [
  // User Controller APIs
  {
    id: 'user-profile-get',
    category: 'User',
    method: 'GET',
    path: '/api/users/profile',
    summary: 'Fetch current authenticated user profile details',
    access: 'Authenticated',
    responseBody: `{\n  "success": true,\n  "message": "Profile fetched successfully",\n  "data": {\n    "id": 1,\n    "firstName": "Sandeep",\n    "lastName": "Prasad",\n    "email": "sandeepkumarprasad01@gmail.com"\n  },\n  "timestamp": "2026-07-25T19:19:50.413Z"\n}`,
    curlExample: `curl -X GET http://localhost:8080/api/users/profile \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>"`,
  },
  {
    id: 'user-profile-update',
    category: 'User',
    method: 'PUT',
    path: '/api/users/profile',
    summary: 'Update first and last name for authenticated user profile',
    access: 'Authenticated',
    requestBody: `{\n  "firstName": "Sandeep",\n  "lastName": "Prasad"\n}`,
    responseBody: `{\n  "success": true,\n  "message": "Profile updated successfully",\n  "data": {\n    "id": 1,\n    "firstName": "Sandeep",\n    "lastName": "Prasad",\n    "email": "sandeepkumarprasad01@gmail.com"\n  },\n  "timestamp": "2026-07-25T19:19:50.417Z"\n}`,
    curlExample: `curl -X PUT http://localhost:8080/api/users/profile \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>" \\\n  -H "Content-Type: application/json" \\\n  -d '{"firstName":"Sandeep","lastName":"Prasad"}'`,
  },

  // Product Controller APIs
  {
    id: 'products-get-all',
    category: 'Product',
    method: 'GET',
    path: '/api/products',
    summary: 'Get all products in store catalog',
    access: 'Public',
    responseBody: `[\n  {\n    "id": 101,\n    "name": "Noise Cancelling Headphones",\n    "description": "Premium Wireless ANC",\n    "price": 299.99,\n    "sku": "TECH-HEAD-001",\n    "stockQuantity": 45,\n    "imageUrl": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",\n    "categoryId": 1,\n    "categoryName": "Audio & Electronics"\n  }\n]`,
    curlExample: `curl -X GET http://localhost:8080/api/products`,
  },
  {
    id: 'products-get-by-id',
    category: 'Product',
    method: 'GET',
    path: '/api/products/{id}',
    summary: 'Get single product detail entry by ID',
    access: 'Public',
    responseBody: `{\n  "id": 101,\n  "name": "Noise Cancelling Headphones",\n  "description": "Premium Wireless ANC",\n  "price": 299.99,\n  "sku": "TECH-HEAD-001",\n  "stockQuantity": 45,\n  "imageUrl": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",\n  "categoryId": 1,\n  "categoryName": "Audio & Electronics"\n}`,
    curlExample: `curl -X GET http://localhost:8080/api/products/101`,
  },
  {
    id: 'products-create',
    category: 'Product',
    method: 'POST',
    path: '/api/products',
    summary: 'Create a new product catalog item',
    access: 'Authenticated',
    requestBody: `{\n  "name": "Ultra Smart Watch",\n  "description": "Titanium casing with AMOLED screen",\n  "price": 349.00,\n  "stockQuantity": 30,\n  "imageUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30",\n  "sku": "TECH-SMART-006",\n  "categoryId": 1\n}`,
    responseBody: `{\n  "id": 107,\n  "name": "Ultra Smart Watch",\n  "description": "Titanium casing with AMOLED screen",\n  "price": 349.00,\n  "sku": "TECH-SMART-006",\n  "stockQuantity": 30,\n  "imageUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30",\n  "categoryId": 1,\n  "categoryName": "Audio & Electronics"\n}`,
    curlExample: `curl -X POST http://localhost:8080/api/products \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>" \\\n  -H "Content-Type: application/json" \\\n  -d '{"name":"Ultra Smart Watch","description":"Titanium","price":349.00,"stockQuantity":30,"imageUrl":"https://...","sku":"TECH-SMART-006","categoryId":1}'`,
  },
  {
    id: 'products-update',
    category: 'Product',
    method: 'PUT',
    path: '/api/products/{id}',
    summary: 'Update an existing product item by ID',
    access: 'Authenticated',
    requestBody: `{\n  "name": "Updated Wireless Headphones",\n  "description": "Updated ANC details",\n  "price": 279.99,\n  "stockQuantity": 50,\n  "imageUrl": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",\n  "sku": "TECH-HEAD-001",\n  "categoryId": 1\n}`,
    responseBody: `{\n  "id": 101,\n  "name": "Updated Wireless Headphones",\n  "description": "Updated ANC details",\n  "price": 279.99,\n  "sku": "TECH-HEAD-001",\n  "stockQuantity": 50,\n  "imageUrl": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",\n  "categoryId": 1,\n  "categoryName": "Audio & Electronics"\n}`,
    curlExample: `curl -X PUT http://localhost:8080/api/products/101 \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>" \\\n  -H "Content-Type: application/json" \\\n  -d '{"name":"Updated Wireless Headphones","price":279.99,"stockQuantity":50}'`,
  },
  {
    id: 'products-delete',
    category: 'Product',
    method: 'DELETE',
    path: '/api/products/{id}',
    summary: 'Delete a product entry by ID (HTTP 204 No Content)',
    access: 'Authenticated',
    curlExample: `curl -X DELETE http://localhost:8080/api/products/101 \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>"`,
  },
  {
    id: 'products-bulk-create',
    category: 'Product',
    method: 'POST',
    path: '/api/products/bulk',
    summary: 'Create multiple product entries in a single request',
    access: 'Authenticated',
    requestBody: `[\n  {\n    "name": "Keyboard A",\n    "description": "Mechanical keybed",\n    "price": 120.00,\n    "stockQuantity": 15,\n    "imageUrl": "https://images.unsplash.com/photo-1587829741301-dc798b83add3",\n    "sku": "KEY-001",\n    "categoryId": 2\n  }\n]`,
    responseBody: `[\n  {\n    "id": 108,\n    "name": "Keyboard A",\n    "description": "Mechanical keybed",\n    "price": 120.00,\n    "sku": "KEY-001",\n    "stockQuantity": 15,\n    "imageUrl": "https://images.unsplash.com/photo-1587829741301-dc798b83add3",\n    "categoryId": 2,\n    "categoryName": "Computers & Accessories"\n  }\n]`,
    curlExample: `curl -X POST http://localhost:8080/api/products/bulk \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>" \\\n  -H "Content-Type: application/json" \\\n  -d '[{"name":"Keyboard A","price":120.00,"stockQuantity":15,"sku":"KEY-001","categoryId":2}]'`,
  },

  // Auth Controller APIs
  {
    id: 'auth-login',
    category: 'Auth',
    method: 'POST',
    path: '/api/auth/login',
    summary: 'Authenticate credentials and return JWT Access & Refresh Tokens',
    access: 'Public',
    requestBody: `{\n  "email": "sandeepkumarprasad01@gmail.com",\n  "password": "Password123!"\n}`,
    responseBody: `{\n  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYW5kZWVw...",\n  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.ref.eyJzdWIiOiJzYW5kZWVw...",\n  "tokenType": "Bearer",\n  "expiresIn": 86400\n}`,
    curlExample: `curl -X POST http://localhost:8080/api/auth/login \\\n  -H "Content-Type: application/json" \\\n  -d '{"email":"sandeepkumarprasad01@gmail.com","password":"Password123!"}'`,
  },
  {
    id: 'auth-register',
    category: 'Auth',
    method: 'POST',
    path: '/api/auth/register',
    summary: 'Register new user account and generate email verification token',
    access: 'Public',
    requestBody: `{\n  "firstName": "Sandeep",\n  "lastName": "Prasad",\n  "email": "sandeepkumarprasad01@gmail.com",\n  "password": "Password123!"\n}`,
    responseBody: `{\n  "message": "User registered successfully! Please check your email for verification.",\n  "verificationToken": "vtoken_98234a_token_demo"\n}`,
    curlExample: `curl -X POST http://localhost:8080/api/auth/register \\\n  -H "Content-Type: application/json" \\\n  -d '{"firstName":"Sandeep","lastName":"Prasad","email":"sandeepkumarprasad01@gmail.com","password":"Password123!"}'`,
  },
  {
    id: 'auth-verify-email',
    category: 'Auth',
    method: 'GET',
    path: '/api/auth/verify-email?token={token}',
    summary: 'Verify email token and enable user account',
    access: 'Public',
    responseBody: `{}`,
    curlExample: `curl -X GET "http://localhost:8080/api/auth/verify-email?token=vtoken_98234a_token_demo"`,
  },
  {
    id: 'auth-resend-verification',
    category: 'Auth',
    method: 'POST',
    path: '/api/auth/resend-verification',
    summary: 'Resend email verification token to user email',
    access: 'Public',
    requestBody: `{\n  "email": "sandeepkumarprasad01@gmail.com"\n}`,
    responseBody: `{\n  "message": "Verification email resent successfully"\n}`,
    curlExample: `curl -X POST http://localhost:8080/api/auth/resend-verification \\\n  -H "Content-Type: application/json" \\\n  -d '{"email":"sandeepkumarprasad01@gmail.com"}'`,
  },
  {
    id: 'auth-forgot-password',
    category: 'Auth',
    method: 'POST',
    path: '/api/auth/forgot-password',
    summary: 'Request password reset token dispatched to user email',
    access: 'Public',
    requestBody: `{\n  "email": "sandeepkumarprasad01@gmail.com"\n}`,
    responseBody: `"Password reset token dispatched to sandeepkumarprasad01@gmail.com"`,
    curlExample: `curl -X POST http://localhost:8080/api/auth/forgot-password \\\n  -H "Content-Type: application/json" \\\n  -d '{"email":"sandeepkumarprasad01@gmail.com"}'`,
  },
  {
    id: 'auth-reset-password',
    category: 'Auth',
    method: 'POST',
    path: '/api/auth/reset-password',
    summary: 'Reset password using valid verification token',
    access: 'Public',
    requestBody: `{\n  "token": "reset_token_demo_77182",\n  "newPassword": "NewSecurePassword123!"\n}`,
    responseBody: `"Password reset successfully"`,
    curlExample: `curl -X POST http://localhost:8080/api/auth/reset-password \\\n  -H "Content-Type: application/json" \\\n  -d '{"token":"reset_token_demo_77182","newPassword":"NewSecurePassword123!"}'`,
  },
  {
    id: 'auth-change-password',
    category: 'Auth',
    method: 'PUT',
    path: '/api/auth/change-password',
    summary: 'Change password for currently authenticated user',
    access: 'Authenticated',
    requestBody: `{\n  "currentPassword": "Password123!",\n  "newPassword": "NewPassword123!",\n  "confirmPassword": "NewPassword123!"\n}`,
    responseBody: `"Password changed successfully"`,
    curlExample: `curl -X PUT http://localhost:8080/api/auth/change-password \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>" \\\n  -H "Content-Type: application/json" \\\n  -d '{"currentPassword":"Password123!","newPassword":"NewPassword123!","confirmPassword":"NewPassword123!"}'`,
  },
  {
    id: 'auth-logout',
    category: 'Auth',
    method: 'POST',
    path: '/api/auth/logout',
    summary: 'Logout user and invalidate active session tokens',
    access: 'Authenticated',
    responseBody: `{\n  "success": true,\n  "message": "User logged out successfully",\n  "data": "Logged out",\n  "timestamp": "2026-07-25T19:19:50.456Z"\n}`,
    curlExample: `curl -X POST http://localhost:8080/api/auth/logout \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>"`,
  },

  // Role Controller APIs
  {
    id: 'roles-get-all',
    category: 'Role',
    method: 'GET',
    path: '/api/roles',
    summary: 'Get list of all system roles',
    access: 'ROLE_ADMIN',
    responseBody: `[\n  {\n    "id": 1,\n    "name": "ROLE_USER",\n    "description": "Standard Customer Access"\n  },\n  {\n    "id": 2,\n    "name": "ROLE_ADMIN",\n    "description": "Administrative Store Operator"\n  }\n]`,
    curlExample: `curl -X GET http://localhost:8080/api/roles \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>"`,
  },
  {
    id: 'roles-create',
    category: 'Role',
    method: 'POST',
    path: '/api/roles',
    summary: 'Create a new security role',
    access: 'ROLE_ADMIN',
    requestBody: `{\n  "name": "ROLE_MANAGER",\n  "description": "Catalog Manager"\n}`,
    responseBody: `{\n  "id": 3,\n  "name": "ROLE_MANAGER",\n  "description": "Catalog Manager"\n}`,
    curlExample: `curl -X POST http://localhost:8080/api/roles \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>" \\\n  -H "Content-Type: application/json" \\\n  -d '{"name":"ROLE_MANAGER","description":"Catalog Manager"}'`,
  },
  {
    id: 'roles-assign',
    category: 'Role',
    method: 'POST',
    path: '/api/roles/assign',
    summary: 'Assign role to a user by userId and roleId',
    access: 'ROLE_ADMIN',
    requestBody: `{\n  "userId": 1,\n  "roleId": 2\n}`,
    responseBody: `"Role assigned successfully to user"`,
    curlExample: `curl -X POST http://localhost:8080/api/roles/assign \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>" \\\n  -H "Content-Type: application/json" \\\n  -d '{"userId":1,"roleId":2}'`,
  },
  {
    id: 'roles-remove',
    category: 'Role',
    method: 'DELETE',
    path: '/api/roles/remove?userId={userId}&roleId={roleId}',
    summary: 'Remove role from user by userId and roleId query parameters',
    access: 'ROLE_ADMIN',
    responseBody: `"Role removed successfully from user"`,
    curlExample: `curl -X DELETE "http://localhost:8080/api/roles/remove?userId=1&roleId=2" \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>"`,
  },

  // Test Controller APIs
  {
    id: 'test-public',
    category: 'Test',
    method: 'GET',
    path: '/api/test/public',
    summary: 'Public test endpoint open to all unauthenticated requests',
    access: 'Public',
    responseBody: `"Public endpoint response: Connection OK"`,
    curlExample: `curl -X GET http://localhost:8080/api/test/public`,
  },
  {
    id: 'test-private',
    category: 'Test',
    method: 'GET',
    path: '/api/test/private',
    summary: 'Private test endpoint requiring valid JWT authorization header',
    access: 'Authenticated',
    responseBody: `"Private endpoint response: Access granted for authorized token"`,
    curlExample: `curl -X GET http://localhost:8080/api/test/private \\\n  -H "Authorization: Bearer <JWT_ACCESS_TOKEN>"`,
  },
];
